
DROP TABLE IF EXISTS "patient";

CREATE TABLE "patient" (
	id SERIAL PRIMARY KEY,
  	name TEXT
);

insert into patient (name) values ('Letta Barthelemy');
insert into patient (name) values ('Elwood Storr');
insert into patient (name) values ('Alvis Sewall');
insert into patient (name) values ('Rudolfo Wilprecht');
insert into patient (name) values ('Aylmer Daniells');
insert into patient (name) values ('Aleta Delaprelle');
insert into patient (name) values ('Thorvald Brame');
insert into patient (name) values ('Tracy Danaher');
insert into patient (name) values ('Pat Letixier');
insert into patient (name) values ('Minetta Breacher');
insert into patient (name) values ('Natassia Duffy');
insert into patient (name) values ('Hinze Francesch');
insert into patient (name) values ('Shelbi Gummie');
insert into patient (name) values ('Katrina Gatrill');
insert into patient (name) values ('Randie Larmor');
insert into patient (name) values ('Clare Niland');
insert into patient (name) values ('Parry Smalles');
insert into patient (name) values ('Ado Chilvers');
insert into patient (name) values ('Rhianna Dericut');
insert into patient (name) values ('Wendall Wycliffe');
insert into patient (name) values ('Bobinette Boken');
insert into patient (name) values ('Jerome McCarrell');
insert into patient (name) values ('Pippy Steggals');
insert into patient (name) values ('Elva Brant');
insert into patient (name) values ('Bertha Simko');
insert into patient (name) values ('Levon Simonini');
insert into patient (name) values ('Raychel Frensch');
insert into patient (name) values ('Patrizio Payne');
insert into patient (name) values ('Redd Spiers');
insert into patient (name) values ('Maynord Zarfat');
insert into patient (name) values ('Camella Tams');
insert into patient (name) values ('Violetta Kernoghan');
insert into patient (name) values ('Mommy Purcell');
insert into patient (name) values ('Gayleen Farris');
insert into patient (name) values ('Hamnet Goomes');
insert into patient (name) values ('Irwinn Jonin');
insert into patient (name) values ('Ase Curnow');
insert into patient (name) values ('Kiersten Rawes');
insert into patient (name) values ('Issy Oakton');
insert into patient (name) values ('Jessy Fleisch');
insert into patient (name) values ('Amberly Muldoon');
insert into patient (name) values ('Trever Paulot');
insert into patient (name) values ('Xylia Suett');
insert into patient (name) values ('Aurora McBrier');
insert into patient (name) values ('Glynn Le Houx');
insert into patient (name) values ('Noach Rosell');
insert into patient (name) values ('Peggi Templar');
insert into patient (name) values ('Devora Guerreru');
insert into patient (name) values ('Liam Erswell');
insert into patient (name) values ('Danie Parks');
insert into patient (name) values ('Leroy Farndale');
insert into patient (name) values ('Hedwiga Unstead');
insert into patient (name) values ('Aldrich Klemensiewicz');
insert into patient (name) values ('Sosanna Dewdney');
insert into patient (name) values ('Fara Legat');
insert into patient (name) values ('Alex Fidele');
insert into patient (name) values ('Bernardo Mathelin');
insert into patient (name) values ('Nariko Deem');
insert into patient (name) values ('Christoffer De Rechter');
insert into patient (name) values ('Alberto Kernley');
insert into patient (name) values ('Gertruda Kiddell');
insert into patient (name) values ('Cloe Faill');
insert into patient (name) values ('Tasia Salvatore');
insert into patient (name) values ('Wood Carder');
insert into patient (name) values ('Alvan Taberner');
insert into patient (name) values ('Emmi Wathell');
insert into patient (name) values ('Carly Beedham');
insert into patient (name) values ('Lefty Bransom');
insert into patient (name) values ('Dilly Luppitt');
insert into patient (name) values ('Aristotle Cullinan');
insert into patient (name) values ('Norene Fader');
insert into patient (name) values ('Starr Marwood');
insert into patient (name) values ('Leonore Bosson');
insert into patient (name) values ('Sheryl Eves');
insert into patient (name) values ('Jarred Springate');
insert into patient (name) values ('Josefa MacIllrick');
insert into patient (name) values ('Sharlene Gunderson');
insert into patient (name) values ('Schuyler Wynett');
insert into patient (name) values ('Charisse Baldock');
insert into patient (name) values ('Maxine Effaunt');
insert into patient (name) values ('Ingram Simonnot');
insert into patient (name) values ('Gretchen Kuschek');
insert into patient (name) values ('Kelila Loxley');
insert into patient (name) values ('Thain Gemelli');
insert into patient (name) values ('Lynnet Caig');
insert into patient (name) values ('Inna Gateman');
insert into patient (name) values ('Maddy Malan');
insert into patient (name) values ('Bucky Eades');
insert into patient (name) values ('Benyamin Bilbery');
insert into patient (name) values ('Freeland Kiff');
insert into patient (name) values ('Olivero Waitland');
insert into patient (name) values ('Hamilton L''Archer');
insert into patient (name) values ('Giorgia Bayley');
insert into patient (name) values ('Timmy Sigge');
insert into patient (name) values ('Renie Orrah');
insert into patient (name) values ('Bastian Sich');
insert into patient (name) values ('Graehme Richin');
insert into patient (name) values ('Noach McMillan');
insert into patient (name) values ('Anny Tainton');
insert into patient (name) values ('Minette Stavers');
